# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160819_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpc',
            name='aws_id',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
