# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160819_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='aws_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='subnet',
            name='availability_zone',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='vpc',
            name='aws_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
