# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160819_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpc',
            name='region',
            field=models.CharField(default='', max_length=30),
        ),
    ]
